name: AI Review Automation
description: "Review Code by Gemini when a PR is not reviewed by anyone until an hour"
inputs:
  token:
    description: "Token"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
