spring:
  application:
    name: fit-friends
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:  jdbc:mariadb://address=(protocol=${DATASOURCE_PROTOCOL})(host=${DATASOURCE_HOST})(port=${DATASOURCE_PORT})/${DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

google:
  client:
    id: ${GOOGLE_CLIENTID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: ${GOOGLE_REDIRECT_URI}
  base:
    uri: ${GOOGLE_BASE_URI}
  token_uri: ${GOOGLE_TOKEN_URI}
  userInfo_uri: ${GOOGLE_USERINFO_URI}
logging:
  level:
    com.example.fit_friends: DEBUG