name: AI Review Automation
on:
  schedule:
    - cron: "0 * * * *" # 1시간마다 실행
  workflow_dispatch:

jobs:
  ai-review:
    runs-on: [ubuntu-latest]
    steps:
      - name: Review
        uses: adorableco/Fit_Friends@ai-review-automation
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GEMINI_KEY: ${{secrets.GEMINI_KEY}}

      - name: Check Directory
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -R

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: review-log
          path: logs
