# @format

name: Coderabbit Review
on:
  schedule:
    - cron: "*/5 * * * *" # 5분마다 실행
jobs:
  coderabbit-review:
    runs-on: [ubuntu-latest]
    steps:
      - name: Review
        uses: adorableco/Fit_Friends@coderabbit-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
